POLICY_KEYWORDS = {
    "A Safe and Fair City": [
        "safe and fair city",
        "safe",
        "public safety",
        "safety",
        "nypd",
        "police",
        "cops",
        "crime",
        "violence interrupter",
        "violence",
        "commissioner",
        "justice",
        "eric garner",
        "kalief browder",
        "layleen polanco",
    ],
    "An Affordable City": [
        "affordable city",
        "affordability",
        "affordable",
        "nycha",
        "housing",
        "public housing",
        "development",
        "home",
        "building",
        "landlord",
        "apartment",
        "rent",
        "tenant",
        "community land trusts",
        "clt",
        "land acquisition",
        "vacant public lots",
        "co living",
        "single-room occupancy",
    ],
    "A Healthy New York": [
        "healthy new york",
        "healthy",
        "health",
        "healthcare",
        "prevention",
        "treatment",
        "substance misuse",
        "substance abuse",
        "primary care",
        "medicaid",
    ],
    "Our Environment":  [
        "environment",
        "environmental",
        "climate change",
        "climate",
        "temperature",
        "sustainable",
        "rising sea levels",
        "electrifying",
        "electric",
        "clean air",
        "fresh air",
        "hurricane",
        "sandy",
        "community retrofit",
        "coolroofs",
        "urban agriculture",
    ],
    "Own Our Transportation": [
        "transportation",
        "subway",
        "bus",
        "bike",
        "transit network",
        "transit",
        "bus rapid transit",
        "street redesign",
        "street",
        "mta",
        "fair fares"
    ],
    "Fact-Based Governance": [
        "fact based governance",
        "governance",
        "leader",
        "administration",
        "transparent",
        "ethical",
        "election reform",
        "ranked choice voting",
        "ranked choice",
        "budget",
        "freedom of information"
        "foil",
    ],
    "A Sanctuary City": [
        "sanctuary city",
        "sanctuary",
        "immigration court",
        "immigrant",
        "ice",
        "undocumented",
        "immigrant family unity project",
        "new york immigrant family unity project",
        "nyc care",
        "language access",
        "language",
    ],
    "A Basic Income for New York City": [
        "basic income for new york city",
        "basic income for nyc",
        "basic income",
        "universal basic income",
        "minimum income",
        "guaranteed income",
        "ubi",
        "freedom dividend",
        "2000",
        "5000",
        "homelessness",
        "inequality",
        "poverty",
        "idnyc",
        "snap",
        "tanf",
        "housing assistance",
        "housing subsidies",
        "tax credits",
        "cash relief",
        "cash",
        "direct cash",
        "human resources administration",
        "hra",
        "homeless services",
        "probation",
    ],
    "Broadband Access": [
        "broadband access",
        "broadband",
        "connectivity",
        "connect",
        "5g",
        "wifi",
        "internet",
        "telehealth",
        "bklyn reach",
        "bklyn",
        "fcc",
    ],
    "Reopening Stronger Schools": [
        "reopening stronger schools",
        "reopening schools",
        "open schools",
        "close schools",
        "school",
        "public school",
        "remote education",
        "education",
        "student",
        "teacher",
        "bridge programming",
        "shsat",
        "evaluation",
        "grades",
        "interviews",
        "essays",
        "learning",
        "universal pre k",
        "3 k",
        "daycare",
        "child care",
        "literacy",
    ],
    "Bringing Back New York's Economy": [
        "new york's economy"
        "economy",
        "business",
        "commerce",
        "big box",
        "finance",
        "gdp",
        "unemployment",
        "banking",
        "people's bank of nyc",
        "people's bank",
        "paychecks",
        "tax breaks",
        "madison square garden",
        "msg",
        "startups",
        "borough bucks",
        "salt deduction",
        "salt",
    ],
    "Culture, Society, and Nightlife": [
        "culture",
        "society",
        "nightlife",
        "restaurants",
        "bars",
        "music venues",
        "media",
        "arts",
        "museums",
        "theaters",
        "concert halls",
        "sports arenas",
        "events",
        "outdoor dining",
        "outdoor performances",
        "cocktails",
        "parks department",
        "city hall",
        "legalization",
        "marijuana",
        "post covid celebration",
        "celebration",
    ],
    "Relief for Our Small Businesses": [
        "small businesses",
        "consumer affairs",
        "vacancy tax",
        "loan program",
        "licenses",
        "permit",
        "office of mwbes",
        "mwbes",
        "cure",
        "collaborative uniform repair enforcement",
        "worker cooperatives",
        "wcbdi",
        "food delivery",
        "non profit",
        "spending vouchers",
        "consumer coupons",
        "land swaps",
        "pay it forward",
        "akron",
        "cinch",
        "regulated hardware",
        "dob",
        "fdny",
        "dca",
        "mome",
        "dohmh",
        "dep",
    ],
    "Effective, Equitable Vaccine Distribution": [
        "equitable vaccine distribution",
        "vaccine distribution",
        "vaccine verification",
        "vaccine",
        "verification",
        "vaccination access",
        "covid recovery",
        "covid",
        "coronavirus",
        "pandemic",
        "availability",
        "repurpose underutilized",
        "underutilized",
        "retrofit",
        "mobile facilities",
        "mobile food trucks",
        "universal data sharing",
        "data sharing",
        "javits center",
        "health and hospitals",
        "h+h",
        "web portal",
        "signup",
        "nyc app",
        "public health playbook",
    ],
    "Recovering from the Mental Health Impacts of COVID-19": [
        "recovering from the mental health impacts",
        "mental health impacts",
        "mental health centers",
        "mental health providers",
        "mental health",
        "behavioral health",
        "co response teams",
        "social workers",
        "school based health centers",
        "sbhc",
        "home-stat",
    ],
    "Racial Equity in Healthcare Delivery": [
        "racial equity",
        "racial inequities"
        "healthcare delivery",
        "healthcare careers",
        "department of health and mental hygiene",
        "dohmh",
        "new york city charter",
        "public health workforce",
        "fair staffing ratios",
        "callen lorde",
        "planned parenthood",
        "crisis pregnancy centers",
        "mary bassett",
        "neighborhood action centers",
        "doula care",
        "maternal mortality",
        "nyc care",
        "independent budget office",
        "ibo",
        "gun violence",
        "cure violence",
        "common justice",
    ]
}
