POLICY_KEYWORDS = {
    "Cash Relief & COVID Recovery": [
        "cash relief",
        "covid recovery",
        "coronavirus",
        "covid 19",
        "vaccine",
        "vaccine distribution",
        "pandemic",
    ],
    "A Safe and Fair City": [
        "safe and fair city",
        "safe",
        "public safety",
        "nypd",
        "police",
        "cops",
        "crime",
        "violence",
        "violence interrupter",
        "commissioner",
        "justice",
        "eric garner",
        "kalief browder",
        "layleen polanco",
    ],
    "An Affordable City": [
        "affordable city",
        "affordable",
        "affordability",
        "nycha",
        "housing",
        "public housing",
        "development",
        "home",
        "building",
        "landlord",
        "apartment",
        "rent",
        "tenant",
        "community land trusts",
        "clt",
        "land acquisition",
        "vacant public lots",
        "co living",
        "single-room occupancy",
    ],
    "A Healthy New York": [
        "healthy new york",
        "healthy",
        "health",
        "healthcare",
        "prevention",
        "treatment",
        "substance misuse",
        "substance abuse",
        "primary care",
        "mental health"
        "medicaid",
    ],
    "Our Environment":  [
        "environment",
        "environmental",
        "climate",
        "climate change",
        "temperature",
        "sustainable",
        "rising sea levels",
        "electric",
        "electrifying",
        "clean air",
        "fresh air",
        "hurricane",
        "sandy",
        "community retrofit",
        "coolroofs",
        "urban agriculture",
    ],
    "Own Our Transportation": [
        "transportation",
        "subway",
        "bus",
        "bike",
        "transit",
        "transit network",
        "bus rapid transit",
        "street",
        "street redesign",
        "mta",
        "fair fares"
    ],
    "Fact-Based Governance": [
        "fact based governance",
        "governance",
        "leader",
        "administration",
        "transparent",
        "ethical",
        "election reform",
        "ranked choice voting",
        "budget",
        "foil",
        "freedom of information"
    ],
    "A Basic Income for New York City": [
        "basic income",
        "universal basic income",
        "minimum income",
        "guaranteed income",
        "ubi",
        "freedom dividend",
        "2000",
        "5000",
        "homelessness",
        "inequality",
        "poverty",
        "idnyc",
        "snap",
        "tanf",
        "housing assistance",
        "housing subsidies",
        "tax credits",
        "direct cash",
        "human resources administration",
        "hra",
        "homeless services",
        "probation",
        "immigrant affairs",
    ],
    "Broadband Access": [
        "broadband access",
        "broadband",
        "connect",
        "connectivity",
        "5g",
        "wifi",
        "internet",
        "telehealth",
        "bklyn reach",
        "bklyn",
        "fcc",
    ],
    "Reopening Stronger Schools": [
        "reopening stronger schools",
        "reopening schools",
        "open schools",
        "close schools",
        "school",
        "public school",
        "education",
        "remote education",
        "student",
        "teacher",
        "bridge programming",
        "shsat",
        "evaluation",
        "grades",
        "interviews",
        "essays",
        "learning",
        "universal pre k",
        "3 k",
        "daycare",
        "child care",
        "literacy",
    ],
    "Bringing Back New York's Economy": [
        "new york's economy"
        "economy",
        "business",
        "commerce",
        "e commerce",
        "big box",
        "finance",
        "gdp",
        "unemployment",
        "banking",
        "people's bank",
        "people's bank of nyc",
        "paychecks",
        "tax breaks",
        "msg",
        "madison square garden",
        "startups",
        "borough bucks",
        "salt deduction",
        "salt",
    ],
    "Culture, Society, and Nightlife": [
        "culture",
        "society",
        "nightlife",
        "restaurants",
        "bars",
        "music venues",
        "media",
        "arts",
        "museums",
        "theaters",
        "concert halls",
        "sports arenas",
        "events",
        "outdoor dining",
        "outdoor performances",
        "cocktails",
        "parks department",
        "city hall",
        "legalization",
        "marijuana",
        "post covid",
        "celebration",
        "post covid celebration",
    ],
    "Relief for Our Small Businesses": [
        "small businesses",
        "consumer affairs",
        "vacancy tax",
        "loan program",
        "licenses",
        "permit",
        "office of mwbes",
        "mwbes",
        "cure",
        "collaborative uniform repair enforcement",
        "worker cooperatives",
        "wcbdi",
        "food delivery",
        "non profit",
        "spending vouchers",
        "consumer coupons",
        "land swaps",
        "pay it forward",
        "akron",
        "cinch",
        "regulated hardware",
        "dob",
        "fdny",
        "dca",
        "mome",
        "dohmh",
        "dep",
    ],
}
