POLICY_KEYWORDS = {
    "A Safe and Fair City": [
        "safe and fair city",
        "safe",
        "public safety",
        "safety",
        "nypd",
        "police",
        "cops",
        "crime",
        "violence interrupter",
        "violence",
        "commissioner",
        "justice",
        "eric garner",
        "kalief browder",
        "layleen polanco",
    ],
    "An Affordable City": [
        "affordable city",
        "affordability",
        "affordable",
        "nycha",
        "public housing",
        "development",
        "building",
        "landlord",
        "apartment",
        "rent",
        "tenant",
        "community land trusts",
        "clt",
        "land acquisition",
        "vacant public lots",
        "co living",
        "single-room occupancy",
    ],
    "A Healthy New York": [
        "healthy new york",
        "healthy",
        "health",
        "healthcare",
        "prevention",
        "treatment",
        "substance misuse",
        "substance abuse",
        "primary care",
        "medicaid",
    ],
    "Our Environment":  [
        "environment",
        "environmental",
        "climate change",
        "climate",
        "temperature",
        "sustainable",
        "rising sea levels",
        "electrifying",
        "electric",
        "clean air",
        "fresh air",
        "hurricane",
        "sandy",
        "community retrofit",
        "coolroofs",
        "urban agriculture",
    ],
    "Own Our Transportation": [
        "transportation",
        "subway",
        "bus",
        "bike",
        "transit network",
        "transit",
        "bus rapid transit",
        "street redesign",
        "street",
        "mta",
        "fair fares"
    ],
    "Fact-Based Governance": [
        "fact based governance",
        "governance",
        "leader",
        "administration",
        "transparent",
        "ethical",
        "election reform",
        "ranked choice voting",
        "ranked choice",
        "budget",
        "freedom of information"
        "foil",
    ],
    "A Sanctuary City": [
        "sanctuary city",
        "sanctuary",
        "immigration court",
        "immigrant",
        "ice",
        "undocumented",
        "immigrant family unity project",
        "new york immigrant family unity project",
        "nyc care",
        "language access",
        "language",
    ],
    "A Basic Income for New York City": [
        "basic income for new york city",
        "basic income for nyc",
        "basic income",
        "universal basic income",
        "minimum income",
        "guaranteed income",
        "ubi",
        "freedom dividend",
        "2000",
        "5000",
        "poverty",
        "idnyc",
        "snap",
        "tanf",
        "tax credits",
        "cash relief",
        "cash",
        "direct cash",
        "human resources administration",
        "hra",
    ],
    "Broadband Access": [
        "broadband access",
        "broadband",
        "connectivity",
        "connect",
        "5g",
        "wifi",
        "internet",
        "telehealth",
        "bklyn reach",
        "bklyn",
        "fcc",
    ],
    "Reopening Stronger Schools": [
        "reopening stronger schools",
        "reopening schools",
        "open schools",
        "close schools",
        "school",
        "public school",
        "remote education",
        "education",
        "student",
        "teacher",
        "bridge programming",
        "shsat",
        "evaluation",
        "grades",
        "interviews",
        "essays",
        "learning",
        "universal pre k",
        "daycare",
        "child care",
    ],
    "Bringing Back New York's Economy": [
        "new york's economy"
        "economy",
        "business",
        "commerce",
        "big box",
        "finance",
        "gdp",
        "unemployment",
        "paychecks",
        "tax breaks",
        "madison square garden",
        "msg",
        "startups",
        "borough bucks",
        "salt deduction",
        "salt",
    ],
    "Culture, Society, and Nightlife": [
        "culture",
        "society",
        "nightlife",
        "restaurants",
        "bars",
        "music venues",
        "media",
        "arts",
        "museums",
        "theaters",
        "concert halls",
        "sports arenas",
        "events",
        "outdoor dining",
        "outdoor performances",
        "cocktails",
        "parks department",
        "city hall",
        "legalization",
        "marijuana",
        "post covid celebration",
        "celebration",
    ],
    "Relief for Our Small Businesses": [
        "small businesses",
        "consumer affairs",
        "vacancy tax",
        "loan program",
        "licenses",
        "permit",
        "office of mwbes",
        "mwbes",
        "cure",
        "collaborative uniform repair enforcement",
        "worker cooperatives",
        "wcbdi",
        "food delivery",
        "non profit",
        "spending vouchers",
        "consumer coupons",
        "land swaps",
        "pay it forward",
        "akron",
        "cinch",
        "regulated hardware",
        "dob",
        "fdny",
        "dca",
        "mome",
        "dohmh",
        "dep",
    ],
    "Effective, Equitable Vaccine Distribution": [
        "equitable vaccine distribution",
        "vaccine distribution",
        "vaccine verification",
        "vaccine",
        "verification",
        "vaccination access",
        "covid",
        "coronavirus",
        "pandemic",
        "retrofit",
        "mobile facilities",
        "mobile food trucks",
        "universal data sharing",
        "javits center",
        "health and hospitals",
        "h+h",
        "web portal",
        "nyc app",
        "public health playbook",
    ],
    "Recovering from the Mental Health Impacts of COVID-19": [
        "recovering from the mental health impacts",
        "mental health impacts",
        "mental health centers",
        "mental health providers",
        "mental health",
        "behavioral health",
        "co response teams",
        "social workers",
        "school based health centers",
        "sbhc",
        "home-stat",
    ],
    "Racial Equity in Healthcare Delivery": [
        "racial equity",
        "racial inequities"
        "healthcare delivery",
        "healthcare careers",
        "department of health and mental hygiene",
        "dohmh",
        "new york city charter",
        "public health workforce",
        "fair staffing ratios",
        "callen lorde",
        "planned parenthood",
        "crisis pregnancy centers",
        "mary bassett",
        "neighborhood action centers",
        "doula care",
        "maternal mortality",
        "nyc care",
        "independent budget office",
        "ibo",
        "gun violence",
        "cure violence",
    ],
    "Green Reinvestment in NYCHA": [
        "green reinvestment in nycha",
        "green reinvestment",
        "new york city housing authority",
        "nycha",
        "capital investment",
        "capital repairs",
        "green new deal",
        "climate mobilization act",
        "data for progress",
        "energy retrofits",
        "retrofits",
        "solar",
        "cooling",
        "heating",
        "get cool nyc",
        "clean jobs",
        "green city force",
        "mold",
        "lead",
        "ombudsperson",
    ],
    "Expanding Resident Democracy at NYCHA": [
        "resident democracy at nycha"
        "resident democracy",
        "new york city housing authority",
        "nycha",
        "nycha board",
        "tenant participation activity",
        "tpa",
        "housing and urban development",
        "hud",
        "resident council",
        "city council committee",
        "community-based organization",
        "cbo",
        "allowable overhead",
        "luxury infill development",
        "infill",
        "uniform land use review process",
        "ulurp",
    ],
    "A People's Bank of New York": [
        "people's bank of new york",
        "people's bank",
        "alternative financial services",
        "afs",
        "loans",
        "credit cards",
        "rental leases",
        "banking",
        "unbanked",
        "community development financial institutions",
        "cdfi",
        "credit unions",
        "community banks",
        "minority depository institutions",
        "mdi",
        "public chartered bank",
    ],
    "A Strong Recovery for NYC Restaurants, Bars and Eating Establishments": [
        "a strong recovery",
        "restaurants",
        "bars",
        "eating",
        "establishments",
        "nyc hospitality alliance",
        "restaurants act of 2021",
        "commercial rent tax",
        "regulated hardware",
        "outdoor heaters",
        "dividers",
        "air filtration",
        "times square alliance",
        "outdoor dining",
        "carry out alcohol",
        "food delivery apps",
    ],
    "The Big Apple Corps: Closing the COVID-19 Achievement Gap and Boosting Our City's Workforce": [
        "the big apple corps",
        "closing the covid-19 achievement gap",
        "boosting our city's workforce",
        "americorps program",
        "tutoring",
        "renaissance learning inc",
        "jobs crisis for young people",
        "american rescue plan",
        "national service",
        "corporation for national and community service",
        "cncs",
        "teachers pipeline",
        "inclusive learning",
        "east harlem teaching residency",
    ],
    "A Vision for More Robust Mobility on Staten Island": [
        "a vision for more robust mobility on staten island",
        "staten island",
        "mass transit",
        "biking infrastructure",
        "ferry service",
        "express bus service",
        "bus rapid transit",
        "access a ride",
        "verrazzano",
        "beryl bike share",
    ],
    "Support for NYC's Nightlife and Cultural Sector": [
        "nyc's nightlife and cultural sector",
        "nightlife",
        "cultural sector",
        "new york independent venue association",
        "nyiva",
        "live venues",
        "nightclubs",
        "performers",
        "promoters",
        "pops-up event initiative",
        "collaborative uniform repair enforcement",
        "cure",
        "new york state liquor authority",
        "sla",
        "mediating establishment and neighborhood disputes",
        "mend",
        "agent of change",
        "public arts in residence",
        "pair",
        "music census",
    ],
    "Support for Independent, Freelance and Gig Economy Workers": [
        "freelance",
        "gig economy",
        "department of consumer and worker protection",
        "office of labor policy and standards",
        "olps",
        "mayor's office of media and entertainment",
        "mome",
        "universal portable benefits fund",
    ],
    "Universal Access to Financial Services": [
        "financial services",
        "new york city banking commission",
        "ritchie torres",
    ],
    "Healing the Homelessness Crisis": [
        "homelessness crisis",
        "homelessness",
        "eviction moratorium",
        "eviction",
        "dhs",
        "hpd",
        "clients advisory board",
        "cab",
        "tenant safe harbor act",
        "tsha",
        "emergency eviction and foreclosure prevention act of 2020",
        "eefpa",
        "right to counsel",
        "eviction diversion program",
        "tenants",
        "safe haven beds",
        "psychiatric beds",
        "city family homeless and eviction prevention supplement",
        "cityfheps",
        "home stability support bill",
        "prevention assistance and temporary housing",
        "path",
    ],
    "Create Real Pathways for Long-Term, Permanently Affordable Housing": [
        "affordable housing",
        "new housing new york 25",
        "nhny25",
        "accessory dwelling unit",
        "adu",
        "rent stabilization",
        "new york state housing trust fund corporation",
        "htfc",
        "united4housing",
        "platform for housing",
        "citywide long term plan",
        "department of design and construction",
        "ddc",
        "coliving",
        "microunits ",
        "small efficiency dwelling units",
        "sedu",
    ],
}
