POLICY_KEYWORDS = {
    "The Freedom Dividend": [
        "ubi",
        "freedom dividend",
        "$1000",
        "money",
        "one thousand dollars",
        "universal basic income",
        "Thomas Paine",
        "Martin Luther King",
        "Richard Nixon",
        "Milton Friedman",
        "african americans",
        "reparations",
        "blacks"
    ],
    "Medicare for All": [
        "medicare for all",
        "healthcare",
        "doctors",
        "health",
        "medicine",
        "medical",
        "holistic",
        "public option",
        "single payer",
        "mental health"
    ],
    "Human-Centered Capitalism": [
        "capitalism",
        "human capitalism",
        "human centered capitalism",
        "income",
        "standard of living",
        "life expectancy",
        "childhood success rates",
        "infant mortality",
        "national well-being",
        "mental health",
        "infrastructure",
        "marriage rates and success",
        "incarceration",
        "journalism",
        "dynamism",
        "mobility",
        "public safety",
        "civic engagement",
        "cybersecurity",
        "economic competitiveness",
        "jobs",
        "work"
    ],
    "Robo-Calling Text Line": [
        "technology",
        "robocalls",
        "robo-calling",
        "phone",
        "cellphone",
        "solicitor",
        "soliciting",
        "harassment",
        "FCC",
        "complaint",
        "illegal",
        "crime"
    ],
    "Regulate AI and other Emerging Technologies": [
        "ai",
        "artificial intelligence",
        "technology",
        "regulate",
        "regulation",
        "machine learning",
        "Elon Musk",
        "secretary of technology",
        "silicon valley"
    ],
    "Net Neutrality": [
        "internet",
        "net",
        "utility",
        "web",
        "ISP",
        "comcast",
        "verizon",
        "at&t",
        "t-mobile",
        "sprint",
        "technology"
    ],
    "Making Taxes Fun": [
        "tax",
        "fun",
        "holiday",
        "federal holiday",
        "federal",
        "irs",
        "revenue",
        "revenue day",
        "economy"
    ],
    "Media Fragmentation": [
        "media responsibility task force",
        "media",
        "press",
        "facts",
        "fact checking",
        "facebook",
        "twitter",
        "social media",
        "russia",
        "russian intervention",
        "foreign intervention",
        "intervention"
    ],
    "Economic Crime": [
        "legal",
        "justice",
        "finance",
        "fraud",
        "wall street",
        "market",
        "free market",
        "abuse",
        "protection",
        "mortgage",
        "financial crisis",
        "recession",
        "illegal"
    ],
    "Modern Time Banking": [
        "society",
        "volunteering",
        "shelter",
        "community",
        "community engagement",
        "tutor",
        "coaching",
        "town fair",
        "social cohesion"
    ],
    "Modernize Voting": [
        "voting",
        "vote",
        "fairness",
        "security",
        "polling",
        "blockchain",
        "effective government",
        "democracy",
        "elections"
    ],
    "Nuclear Energy": [
        "energy",
        "nuclear",
        "green new deal",
        "sustainability",
        "environment",
        "carbon",
        "carbon-free",
        "electricity",
        "electric"
    ],
    "Algorithmic Trading/Fraud": [
        "CFTC",
        "trading",
        "crime",
        "fraud",
        "market",
        "free market",
        "algorithms",
        "equity",
        "accountability",
        "investigation",
        "illegal",
        "technology"
    ],
    "Zoning": [
        "society",
        "housing",
        "affordable",
        "zoning laws",
        "local",
        "development",
        "home ownership",
        "housing cost",
        "rent",
        "buy",
        "laws"
    ],
    "Entice High-Skill Individuals": [
        "h1b",
        "f1",
        "H1-B",
        "F-1",
        "visa",
        "immigrant",
        "immigration",
        "jobs",
        "work"
    ],
    "American Mall Act": [
        "mall",
        "community",
        "community center",
        "socialization",
        "commerce",
        "amazon",
        "investments",
        "economy",
        "local",
        "retail",
        "buildings",
        "blight",
        "jobs",
        "work"
    ],
    "Tort Reform/Reasonableness Dismissals": [
        "legal",
        "litigation",
        "tort",
        "lawsuit",
        "justice",
        "court",
        "crime",
        "judge",
        "appeal",
        "laws"
    ],
    "Financial Transaction Tax": [
        "taxes",
        "tax",
        "finance",
        "bubble",
        "economy",
        "market",
        "stock",
        "trade",
        "fund",
        "mutual fund"
    ],
    "File Income Taxes": [
        "taxes",
        "tax",
        "turbotax",
        "efile",
        "e-file",
        "tax prep",
        "IRS",
        "automation",
        "treasury",
        "economy"
    ],
    "Capital Gain/Carried Interest Tax": [
        "tax",
        "taxes",
        "interest",
        "tax code",
        "revenue",
        "carried",
        "interest",
        "loophole",
        "capital",
        "gain",
        "economy"
    ],
    "Ease the Transition to Self-Driving Vehicles": [
        "cars",
        "technology",
        "self-driving",
        "self driving",
        "vehicles",
        "truck",
        "truck driving",
        "trucker",
        "automation",
        "jobs",
        "work",
        "trucking czar",
        "transition",
        "tax",
        "taxes"
    ],
    "Implement Mandatory Paid Leave Policy": [
        "paid leave",
        "parent",
        "family",
        "families",
        "moms",
        "mothers",
        "dads",
        "fathers",
        "community",
        "children",
        "child",
        "childcare",
        "mental health",
        "stress",
        "leave",
        "mandatory leave",
        "jobs",
        "work",
        "productivity",
        "workers",
        "workers' rights"
    ],
    "Make it Easy for Americans to Move for Work": [
        "home",
        "economy",
        "dynamism",
        "jobs",
        "moving",
        "move",
        "work",
        "subsidy",
        "subsidize",
        "cost",
        "mobility",
        "refund",
        "IRS",
        "federal",
        "profession"
    ],
    "Modernize Military Spending": [
        "military",
        "spending",
        "modern",
        "modernization",
        "soldiers",
        "veterans",
        "mental health",
        "cyberterrorism",
        "nuclear material",
        "Legion of Builders and Destroyers",
        "VA",
        "Veterans Health Administration",
        "warriors",
        "army",
        "navy",
        "air force"
    ],
    "Veteran Employment and Businesses": [
        "veterans",
        "soldiers",
        "employment",
        "business",
        "businesses",
        "military"
    ],
    "Ending Veteran Suicide": [
        "suicide",
        "veterans",
        "soldiers",
        "PTSD",
        "mental health",
        "crisis lines",
        "suicide hotlines",
        "gun suicide",
        "gun storage",
        "gun lockers"
    ],
    "Every Vet Under a Roof Initiative": [
        "veterans",
        "soldiers",
        "housing",
        "roof",
        "homeless",
        "homelessness",
        "civilian",
        "transition",
        "mortgage"
    ],
    "Controlled Substance Waivers for Veterans": [
        "veterans",
        "soldiers",
        "PTSD",
        "substances",
        "marijuana",
        "controlled substances"
    ],
    "Improving Veteran Health": [
        "veterans",
        "soldiers",
        "health",
        "mental health",
        "choice act",
        "TBI",
        "PTSD",
        "VA",
        "VHA",
        "Veterans Health Administration",
        "rural areas"
    ],
    "Military Training: The Gold Standard": [
        "veterans",
        "soldiers",
        "jobs",
        "CDL",
        "EMT",
        "medics",
        "job transition",
        "civilian transition",
        "training",
        "certification",
        "licensing"
    ],
    "GI Bill Improvements": [
        "veterans",
        "soldiers",
        "schools",
        "higher education",
        "education",
        "course credit",
        "college",
        "university"
    ],
    "Reverse Boot Camp": [
        "veterans",
        "soldiers",
        "civilian life",
        "grocery shopping",
        "financial literacy",
        "finance",
        "jobs",
        "civilian transition"
    ],
    "Life-Skills Education in All High Schools": [
        "education",
        "life skills",
        "life-skills",
        "high schools",
        "schools",
        "finance",
        "jobs",
        "interviews",
        "cooking",
        "food",
        "mental health",
        "time management",
        "physical fitness"
    ],
    "Make Community College Affordable for All": [
        "college",
        "higher education",
        "university",
        "education",
        "student debt",
        "debt",
        "tuition",
        "schools",
        "community",
        "jobs",
        "work",
        "loans"
    ],
    "Free Financial Counseling for All": [
        "finance",
        "financial literacy",
        "counseling",
        "banking",
        "retirement",
        "investments",
        "investing",
        "school",
        "high school",
        "IRS",
        "online course",
        "AI",
        "advisors",
        "personal finance",
        "college",
        "community college",
        "higher education",
        "advice",
        "savings",
        "economy"
    ],
    "Make it Easier to Save for Retirement": [
        "finance",
        "retirement",
        "investing",
        "investments",
        "savings",
        "tax-free",
        "retirement accounts",
        "income",
        "economy"
    ],
    "Support the Revival of Earmarks": [
        "earmarks",
        "legislation",
        "pass legislation",
        "government",
        "federal",
        "house",
        "senate",
        "representatives",
        "senators",
        "revenue",
        "constituents"
    ],
    "Expand Access to Medical Experts": [
        "health",
        "medicine",
        "medical",
        "doctors",
        "physicians",
        "PCP",
        "primary care specialists",
        "IBM",
        "watson",
        "diagnoses",
        "nurse practitioners",
        "heath",
        "healthcare",
        "preventative",
        "maintenance",
        "patients"
    ],
    "Reduce Student Loan Burden": [
        "education",
        "college",
        "university",
        "higher education",
        "loans",
        "lenders",
        "lending",
        "schools",
        "student loans",
        "debt",
        "student debt",
        "burden",
        "borrowers",
        "forgiveness",
        "bankruptcy",
        "bankruptcy laws",
        "10\u00d710 Student Loan Emancipation Act"
    ],
    "Rebuild American Infrastructure": [
        "society",
        "infrastructure",
        "roads",
        "bridges",
        "airports",
        "invest",
        "investments",
        "modernize",
        "automate",
        "power plants",
        "sewers",
        "water systems",
        "clean water",
        "water treatment",
        "flint",
        "fiber-optic",
        "network",
        "internet",
        "high-speed internet",
        "solar",
        "solar-cell roadways",
        "electric",
        "electricity",
        "rebuild america",
        "challenge grant",
        "jobs",
        "sustainability"
    ],
    "Fund Autism Intervention": [
        "medicine",
        "mental health",
        "medical",
        "child",
        "children",
        "health",
        "family",
        "families",
        "moms",
        "mothers",
        "dads",
        "fathers",
        "healthcare",
        "health care",
        "autism",
        "autistic",
        "autism spectrum",
        "CDC",
        "Department of Education"
    ],
    "Fund Medical Technology Innovation": [
        "medicine",
        "medical",
        "technology",
        "technologies",
        "vaccines",
        "antiseptics",
        "antibiotics",
        "innovation",
        "investments",
        "AI",
        "automation",
        "tax incentives",
        "rural",
        "preventative care",
        "care"
    ],
    "Increase Assistance for Single Parents": [
        "society",
        "parenting",
        "parent",
        "children",
        "child",
        "family",
        "moms",
        "mothers",
        "dads",
        "fathers",
        "families",
        "support",
        "support network",
        "single parents",
        "community",
        "housing",
        "communal housing",
        "single mothers",
        "Big Brothers Big Sisters of America",
        "big brother",
        "big sister"
    ],
    "Improve the American Scorecard": [
        "society",
        "mental health",
        "scorecard",
        "america",
        "data",
        "Quality of life",
        "health-adjusted life expectancy",
        "happiness",
        "well-being",
        "mental health",
        "underemployment",
        "income inequality",
        "consumer debt",
        "student debt",
        "work and civic engagement levels",
        "volunteerism",
        "infant mortality",
        "quality of infrastructure",
        "access to education",
        "marriage and divorce rates",
        "substance abuse and related deaths",
        "national optimism",
        "personal dynamism",
        "economic mobility",
        "GDP",
        "directives"
    ],
    "Prevent Airlines from Removing Customers": [
        "society",
        "airlines",
        "airplanes",
        "travel",
        "customers",
        "FAA",
        "removed",
        "removing",
        "safety",
        "auction",
        "seat",
        "airplane seats"
    ],
    "Prosperity Grants": [
        "non-profit",
        "donations",
        "donate",
        "tax",
        "philanthropy",
        "local",
        "community",
        "IRS",
        "tax code",
        "economy"
    ],
    "Automatically Sunset Old Laws": [
        "legal",
        "laws",
        "congress",
        "representatives",
        "senators",
        "KPIs",
        "key performance indicators",
        "sunset period"
    ],
    "Free Marriage Counseling for All": [
        "society",
        "marriage",
        "community",
        "dads",
        "moms",
        "fathers",
        "mothers",
        "family",
        "families",
        "parent",
        "children",
        "child",
        "single parents",
        "happy",
        "happiness",
        "relationships",
        "divorce",
        "counseling",
        "family counseling",
        "ACA",
        "affordable care act",
        "tax code"
    ],
    "Closely Monitor Mental Health of White House Staff": [
        "mental health",
        "healthcare",
        "health care",
        "health",
        "white house",
        "president",
        "vice president",
        "chief of staff",
        "psychiatrists",
        "psychologists",
        "stress",
        "senior government official",
        "emotional",
        "emotions",
        "executive branch",
        "destigmatize mental health issues",
        "white house psychologist corps"
    ],
    "Prevent Corruption among Federal Regulators": [
        "corruption",
        "crime",
        "regulation",
        "government",
        "speaking fees",
        "salary",
        "presidential salary",
        "cabinet members",
        "heads of regulatory agencies",
        "salaries",
        "Bill Clinton",
        "George Bush"
    ],
    "American Exchange Program": [
        "society",
        "exchange",
        "americans",
        "urban",
        "rural",
        "divide",
        "empathy",
        "community",
        "high school",
        "seniors",
        "school",
        "local"
    ],
    "Provide Basic Banking Services through the Post Office": [
        "finance",
        "post office",
        "banking",
        "bank",
        "savings",
        "basic banking services",
        "basic services",
        "loans",
        "lending",
        "economy"
    ],
    "Local Journalism Fund": [
        "journalism",
        "journalists",
        "newspapers",
        "news",
        "writing",
        "local",
        "investments",
        "fact-checking",
        "media",
        "library",
        "libraries",
        "FCC"
    ],
    "Limit Bureaucracy in the Federal Workforce": [
        "government",
        "federal",
        "bureaucracy",
        "federal workers",
        "jobs",
        "millennials",
        "inefficiency",
        "inefficiencies",
        "efficiency",
        "congress",
        "hiring"
    ],
    "Nuclear Launch Decisions": [
        "nuclear missiles",
        "nukes",
        "war",
        "conflict",
        "nuclear attack",
        "attack",
        "security",
        "president",
        "vice president",
        "chief of staff",
        "military"
    ],
    "NCAA Should Pay Athletes": [
        "NCAA",
        "athletes",
        "college",
        "university",
        "higher education",
        "student",
        "sports",
        "basketball",
        "football",
        "college athletes",
        "jobs"
    ],
    "Every Cop Gets a Camera": [
        "legal",
        "justice",
        "crime",
        "laws",
        "police",
        "cop",
        "camera",
        "body camera",
        "transparency",
        "legal",
        "non-lethal",
        "weapons",
        "handprint guns"
    ],
    "Reduce Harm to Children Caused by Smartphones": [
        "smartphones",
        "children",
        "child",
        "social media",
        "parent",
        "dads",
        "moms",
        "mothers",
        "fathers",
        "family",
        "families",
        "community",
        "dark patterns",
        "technology"
    ],
    "American Journalism Fellows": [
        "journalism",
        "journalists",
        "news",
        "newspapers",
        "media",
        "fellowship",
        "news organizations",
        "local",
        "local news",
        "local journalism",
        "investments",
        "grants"
    ],
    "Invest in America\u2019s Mental Health": [
        "mental health",
        "healthcare",
        "health care",
        "health",
        "medicine",
        "medical",
        "treatment",
        "social workers",
        "psychologists",
        "psychiatrists",
        "depression",
        "investments",
        "AI"
    ],
    "Hold Pharmaceutical Companies Accountable": [
        "legal",
        "justice",
        "medicine",
        "medical",
        "crime",
        "big pharma",
        "pharma",
        "monopoly",
        "monopolies",
        "Purdue Pharma",
        "OxyContin",
        "opioids",
        "Fentanyl",
        "pharmaceutical companies",
        "drugs",
        "FDA",
        "DOJ",
        "Food and Drug Administration",
        "Department of Justice",
        "medicare for all",
        "medicare-for-all",
        "medicare",
        "health",
        "healthcare",
        "health care"
    ],
    "Fighting the Rise of White Nationalism and Extremism": [
        "white nationalism",
        "white supremacy",
        "racism",
        "extremism",
        "domestic terrorism",
        "kkk",
        "nazi",
        "terrorism",
        "DOJ",
        "Department of Justice",
        "FBI",
        "Federal Bureau of Investigation",
        "criminal justice"
    ],
    "Value-Added Tax": [
        "vat",
        "value added tax",
        "taxes",
        "new taxes",
        "amazon",
        "facebook",
        "google",
        "economy",
        "market",
        "trade",
        "business",
        "tax code",
        "ubi",
        "freedom dividend",
        "$1000",
        "money",
        "one thousand dollars",
        "universal basic income",
        "10%"
    ],
    "Make Puerto Rico a State": [
        "statehood",
        "puerto rico",
        "natural disasters",
        "citizens",
        "americans",
        "puerto ricans",
        "states rights"
    ],
    "Legalize Marijuana": [
        "420",
        "marijuana",
        "pot",
        "dank",
        "legalization",
        "legal",
        "justice",
        "laws",
        "drugs",
        "enforcement",
        "african americans",
        "blacks",
        "incarceration",
        "forgiveness",
        "pardon",
        "4/20",
        "criminal justice",
        "reform"
    ],
    "Early Childhood Education for All": [
        "children",
        "education",
        "preschools",
        "pre-schools",
        "schools",
        "early",
        "childhood",
        "child",
        "dads",
        "moms",
        "mothers",
        "fathers",
        "family",
        "families",
        "Department of Education",
        "DoE",
        "pre-k",
        "pre-kindergarten"
    ],
    "Increase Teacher Salaries": [
        "teachers",
        "mentors",
        "salary",
        "education",
        "schools",
        "student",
        "universities",
        "higher education",
        "jobs"
    ],
    "Carbon Fee and Dividend": [
        "environment",
        "carbon",
        "carbon fees",
        "greenhouse gasses",
        "green new deal",
        "taxes",
        "tax",
        "fossil fuels",
        "fossil fuel company",
        "fossil fuel companies",
        "coal",
        "oil",
        "fracking"
    ],
    "Promote Vocational Education": [
        "vocational education",
        "higher education",
        "education",
        "vocation",
        "schools",
        "jobs",
        "work",
        "trades",
        "plumber",
        "technician",
        "repairman"
    ],
    "Fight for Equal Pay": [
        "jobs",
        "work",
        "pay",
        "equality",
        "fairness",
        "women's rights",
        "workers' rights",
        "rights",
        "men",
        "women",
        "blacks",
        "african americans",
        "minority",
        "minorities",
        "native americans",
        "hispanic"
    ],
    "Campaign Finance Reform": [
        "campaign",
        "finance",
        "elections",
        "citizens united",
        "vote",
        "voters",
        "voting"
    ],
    "Right to Privacy/Abortion and Contraception": [
        "society",
        "abortion",
        "birth control",
        "contraception",
        "reproductive rights",
        "healthcare",
        "medicine",
        "medical",
        "planned parenthood",
        "women's rights"
    ],
    "Support the DREAM Act": [
        "dreamers",
        "immigration",
        "immigrants",
        "illegal immigration",
        "citizenship",
        "citizen",
        "dream act",
        "reform"
    ],
    "Southern Border Security": [
        "immigration",
        "immigrant",
        "border security",
        "border",
        "security",
        "illegal immigration",
        "illegals",
        "wall",
        "fencing",
        "drones",
        "alien",
        "illegal alien"
    ],
    "Pathway to Citizenship for Undocumented Immigrants": [
        "immigration",
        "immigrant",
        "citizenship",
        "undocumented",
        "illegals",
        "illegal immigrant",
        "alien",
        "illegal alien"
    ],
    "Control the Cost of Higher Education": [
        "education",
        "college",
        "university",
        "community college",
        "higher education",
        "student debt",
        "loans",
        "cost",
        "administrative costs"
    ],
    "Support for the Arts": [
        "creativity",
        "arts",
        "music",
        "film",
        "writing",
        "photography",
        "copyright laws",
        "schools",
        "royalties",
        "musicians",
        "licensing",
        "Music Modernization Act"
    ],
    "Paid Family Leave": [
        "paid leave",
        "parent",
        "moms",
        "dads",
        "fathers",
        "mothers",
        "family",
        "families",
        "community",
        "children",
        "child",
        "childcare",
        "newborn",
        "mental health",
        "stress",
        "leave",
        "mandatory leave",
        "jobs",
        "work",
        "productivity",
        "workers",
        "workers' rights"
    ],
    "Gun Safety": [
        "gun violence",
        "society",
        "guns",
        "2nd amendment",
        "second amendment",
        "2A",
        "NRA",
        "handguns",
        "rifles",
        "shotguns",
        "licensing",
        "license",
        "safety",
        "buyback",
        "gun control",
        "gun safety"
    ],
    "Combating Gun Violence and Hate in America": [
        "gun violence",
        "society",
        "guns",
        "2nd amendment",
        "second amendment",
        "2A",
        "NRA",
        "handguns",
        "rifles",
        "shotguns",
        "licensing",
        "license",
        "safety",
        "buyback",
        "gun control",
        "gun safety"
    ],
    "Foreign Policy First Principles": [
        "foreign policy",
        "foreign",
        "conflict",
        "war",
        "foreign conflict",
        "foreign relations",
        "UN",
        "international relations",
        "foreign issues",
        "NATO",
        "AUMF",
        "congress",
        "DoD",
        "Department of Defense",
        "audit",
        "abroad"
    ],
    "LGBTQ Rights": [
        "society",
        "LGBTQ",
        "lesbian",
        "gay",
        "bisexual",
        "transgender",
        "queer",
        "LGBT",
        "LGBT rights",
        "gender rights",
        "equal rights",
        "equality"
    ],
    "Opioid Crisis": [
        "treatment",
        "medicine",
        "crime",
        "drugs",
        "medical",
        "pills",
        "doctors",
        "heroin",
        "oxycontin",
        "percocet",
        "big pharma",
        "pharma",
        "monopoly",
        "monopolies",
        "Purdue Pharma",
        "OxyContin",
        "opioids",
        "Fentanyl",
        "pharmaceutical companies",
        "drugs",
        "FDA",
        "DOJ",
        "Food and Drug Administration",
        "Department of Justice",
        "medicare for all",
        "medicare-for-all",
        "medicare",
        "health",
        "healthcare",
        "health care"
    ],
    "Reduce Mass Incarceration": [
        "legal",
        "justice",
        "crime",
        "criminal justice",
        "incarceration",
        "african americans",
        "blacks",
        "federal prisons",
        "private prisons",
        "prison",
        "minorities",
        "treatment"
    ],
    "Full Climate Change Plan: It\u2019s Worse Than You Think \u2013 Lower Emissions, Higher Ground": [
        "climate",
        "climate change",
        "green new deal",
        "alternative energy",
        "clean",
        "environment",
        "fossil fuels",
        "solar",
        "wind",
        "nuclear",
        "energy",
        "power plants",
        "greenhouse gasses",
        "global warming",
        "electric bills",
        "EPA",
        "environmental protection agency"
    ],
    "Combat Climate Change": [
        "climate",
        "climate change",
        "green new deal",
        "alternative energy",
        "clean",
        "environment",
        "fossil fuels",
        "solar",
        "wind",
        "nuclear",
        "energy",
        "power plants",
        "greenhouse gasses",
        "global warming",
        "electric bills",
        "EPA",
        "environmental protection agency"
    ],
    "Decriminalize Opioids": [
        "legal",
        "justice",
        "crime",
        "decriminalization",
        "treatment",
        "medicine",
        "drugs",
        "medical",
        "pills",
        "doctors",
        "fentanyl",
        "heroin",
        "oxycontin",
        "percocet"
    ],
    "Ranked Choice Voting": [
        "voting",
        "vote",
        "voters",
        "elections",
        "fairness",
        "ranked choice",
        "third party"
    ],
    "Democracy Dollars": [
        "campaign finance",
        "elections",
        "fairness",
        "reform",
        "voting",
        "voters",
        "vote"
    ],
    "Relocate Federal Agencies": [
        "government",
        "federal agencies",
        "jobs",
        "decentralize",
        "investments"
    ],
    "Extend Daylight Saving Time All Year": [
        "society",
        "daylight savings",
        "time",
        "timezones",
        "time zones",
        "eastern",
        "central",
        "mountain",
        "pacific"
    ],
    "Decrease Pre-Trial Cash Bail": [
        "legal",
        "justice",
        "cost reduction",
        "laws",
        "crime",
        "cash bail",
        "bail",
        "incarcerate",
        "incarceration"
    ],
    "Lower the Voting Age to 16": [
        "sixteen",
        "16",
        "voting",
        "voting age",
        "vote",
        "elections",
        "civil engagement",
        "civic duty",
        "voter turnout"
    ],
    "Revive the Office of Technology Assessment": [
        "technology",
        "advisers",
        "congress",
        "facebook",
        "google",
        "twitter",
        "apple",
        "office of technology assessment",
        "OTA"
    ],
    "18 Year Term Limit for Supreme Court Justices": [
        "court",
        "supreme court",
        "justices",
        "crime",
        "laws",
        "term limits",
        "eighteen years",
        "18",
        "government"
    ],
    "12-Year Congressional Term Limits": [
        "congress",
        "12",
        "term limits",
        "twelve years",
        "government",
        "lawmakers",
        "legislators",
        "laws"
    ],
    "Empowering MMA Fighters": [
        "MMA",
        "mixed martial arts",
        "sports",
        "ali act",
        "unions",
        "national labor relations board",
        "jobs"
    ],
    "Make Election Day a Holiday": [
        "holiday",
        "elections",
        "voting",
        "vote",
        "civic engagement",
        "voters"
    ],
    "The Penny Makes No Cents": [
        "penny",
        "change",
        "cents",
        "finance",
        "economy",
        "cost",
        "waste"
    ],
    "Quantum Computing and Encryption Standards": [
        "technology",
        "investments",
        "modernization",
        "quantum",
        "computers",
        "encryption",
        "NIST",
        "DoD",
        "department of defense"
    ],
    "Public Council of Advisors": [
        "public council",
        "experts",
        "artists",
        "leaders",
        "public opinion",
        "consultants",
        "advisors",
        "advice",
        "guidance",
        "culture"
    ],
    "Reduce Packaging Waste": [
        "waste",
        "amazon",
        "packaging",
        "cardboard",
        "environment",
        "green new deal",
        "cost",
        "environmentalism",
        "economics",
        "EPA",
        "environmental protection agency"
    ],
    "End Partisan Gerrymandering": [
        "elections",
        "voting",
        "voter rights",
        "vote",
        "fairness",
        "gerrymandering",
        "redistricting",
        "democracy"
    ],
    "Make Washington, DC, a State": [
        "states rights",
        "statehood",
        "washington dc",
        "capital",
        "taxation",
        "representation"
    ],
    "Head of Culture and Ceremony": [
        "celebrity",
        "surrogate",
        "culture",
        "ceremony",
        "celebrations"
    ],
    "Grid Modernization Race to the Top": [
        "grid",
        "power plants",
        "electricity",
        "modernization",
        "infrastructure",
        "energy",
        "energy savings",
        "environmentalism",
        "environment"
    ],
    "Automatic Voter Registration": [
        "voting",
        "vote",
        "elections",
        "voters rights",
        "automatic",
        "voter",
        "registration"
    ],
    "Expand Selective Schools": [
        "education",
        "schools",
        "college",
        "university",
        "student",
        "higher education",
        "campus",
        "department of education",
        "DOE",
        "congress",
        "investments"
    ],
    "Proportional Selection of Electors": [
        "electoral college",
        "elections",
        "voting",
        "vote",
        "voters",
        "proportionally",
        "constitutional amendments",
        "amendments"
    ],
    "Crypto/Digital Asset Regulation and Consumer Protection": [
        "crypto",
        "cryptocurrency",
        "bitcoin",
        "etherium",
        "dogecoin",
        "regulation",
        "finance",
        "digital assets",
        "framework",
        "Token Taxonomy Act",
        "technology"
    ],
    "Restoration of Voting Rights": [
        "voting",
        "voting rights",
        "vote",
        "elections",
        "civic engagement",
        "incarceration",
        "probation",
        "parole",
        "criminal justice",
        "post-incarceration",
        "ex-felons",
        "reintegration",
        "reintegrate"
    ],
    "Control the Cost of Prescription Drugs": [
        "health",
        "healthcare",
        "medicine",
        "drugs",
        "prescription",
        "cost",
        "FDA",
        "medicare",
        "prices",
        "drug prices",
        "pricing",
        "NIH"
    ],
    "Reduce Wildfires": [
        "wildfires",
        "environment",
        "investments",
        "US Forest Service",
        "U.S. Forest Service",
        "forest",
        "forest fires",
        "trees",
        "California",
        "EPA",
        "Environmental Protection Agency",
        "congress",
        "legislation",
        "megafires"
    ],
    "Data as a Property Right": [
        "technology",
        "data",
        "personal data",
        "data property",
        "data rights",
        "phones",
        "computers",
        "cellphones",
        "cell phones",
        "facebook",
        "google",
        "amazon",
        "apple",
        "microsoft",
        "social media",
        "data collection",
        "download",
        "congress",
        "laws",
        "legislation"
    ],
    "Timing of Payments for Small Businesses": [
        "business",
        "businesses",
        "corporations",
        "small business",
        "payments",
        "economy",
        "congress",
        "startup",
        "stalling tactics",
        "contracts",
        "market",
        "free market",
        "jobs"
    ],
    "Preservation of Public Lands and Water": [
        "environment",
        "conservation",
        "preservation",
        "lands",
        "water",
        "public",
        "public lands",
        "public water",
        "ecosystem",
        "green new deal",
        "Every Kid in a Park initiative",
        "Secretary of the Interior",
        "natural monuments"
    ],
    "End Bidding Wars for Corporate Relocation": [
        "economy",
        "bidding wars",
        "corporations",
        "businesses",
        "relocation",
        "corporate",
        "companies",
        "company",
        "tax breaks",
        "taxes",
        "corporate welfare",
        "bidding"
    ]
}
